### ISSUE TITLE
Capitalized scheme throws

### ISSUE THREAD

**Issue by Overtorment** [bitcoinjs/bip21#11]
Not sure if it's a valid issue, but 
`bitcoin:1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH?amount=20.3&label=Foobar` decodes fine while `BITCOIN:1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH?amount=20.3&label=Foobar` throws `Invalid BIP21 URI`

**Comment by junderw** [comment]
> The scheme component ("bitcoin:") is case-insensitive, and implementations must accept any combination of uppercase and lowercase letters. The rest of the URI is case-sensitive, including the query parameter keys.

That is a bug.

**Comment by junderw** [comment]
Fixed in #12 v2.0.3
