### ISSUE TITLE
Validate that no comma is used in the amount

### ISSUE THREAD

**Issue by sondreb** [bitcoinjs/bip21#17]
From the BIP21:

`If an amount is provided, it MUST be specified in decimal BTC. All amounts MUST contain no commas and use a period (.) as the separating character to separate whole numbers and decimal fractions. I.e. amount=50.00 or amount=50 is treated as 50 BTC, and amount=50,000.00 is invalid.`

Source: https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki#transfer-amount

May I suggest that extra validation is added if amount contains a comma and throw error?

**Comment by junderw** [comment]
This would be a breaking change to a basically complete and ossified library.

Since the change does not benefit users that follow the spec (it would only punish those who didn't) I don't see much value to this change.

Thanks for the issue.
